import React from 'react';

const PrivacyPolicy = () => {
    return (
        <div className="bg-gray-100 p-6">
            <div className="max-w-2xl mx-auto bg-white p-8 rounded-lg shadow-lg">
                <h1 className="text-2xl font-semibold mb-4">Privacy Policy for Face-Mingle</h1>

                <p className="text-gray-600">Last Updated: Wednesday, October 4, 2023</p>

                <div className="mt-6">
                    <h2 className="text-xl font-semibold">1. Introduction</h2>
                    <p>
                        Welcome to Face-Mingle (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). We are committed to protecting your privacy and ensuring the security
                        of your data when you use our AI-based face-swapping service. This Privacy Policy outlines how we handle user data.
                    </p>
                    <p>
                        By using our service, you acknowledge that we do not collect email addresses, personal details, or any user-specific
                        information. Furthermore, we are not responsible for any content generated by our service that may be controversial
                        or result in legal issues.
                    </p>
                </div>

                <div className="mt-6">
                    <h2 className="text-xl font-semibold">2. Information We Do Not Collect</h2>
                    <p>We do not collect personal information from users, including email addresses or any other personal details.</p>
                </div>

                <div className="mt-6">
                    <h2 className="text-xl font-semibold">3. User-Generated Content</h2>
                    <p>Our service allows you to create user-generated content, such as face-swapped images or videos. We want to emphasize that:</p>
                    <ul className="list-disc list-inside">
                        <li>We do not store or record user-generated content.</li>
                        <li>Users are solely responsible for any content they create or upload using our service.</li>
                        <li>We do not endorse or take responsibility for the accuracy, legality, or appropriateness of user-generated content.</li>
                    </ul>
                </div>

                <div className="mt-6">
                    <h2 className="text-xl font-semibold">4. Security</h2>
                    <p>
                        We employ industry-standard security measures to protect your use of our service. However, it&apos;s important to note that
                        we do not collect or store user-generated content, and we cannot control the dissemination or use of such content once it is created.
                    </p>
                </div>

                <div className="mt-6">
                    <h2 className="text-xl font-semibold">5. Legal Responsibility</h2>
                    <p>We want to make it clear that:</p>
                    <ul className="list-disc list-inside">
                        <li>We are not responsible for any legal issues, controversies, or disputes arising from the use of our service.</li>
                        <li>Users are encouraged to use our service responsibly and in compliance with applicable laws and regulations.</li>
                    </ul>
                </div>

                <div className="mt-6">
                    <h2 className="text-xl font-semibold">6. Changes to this Privacy Policy</h2>
                    <p>We may update this Privacy Policy from time to time. The date of the latest revision will be indicated at the top of this page. We encourage you to review this Privacy Policy periodically.</p>
                </div>

                <div className="mt-6">
                    <h2 className="text-xl font-semibold">7. Contact Us</h2>
                    <p>If you have questions or concerns regarding this Privacy Policy or the use of our service, please contact us at <a href="mailto:shadeersadikeen@gmail.com">shadeersadikeen@gmail.com</a>.</p>
                </div>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
